INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Papier', '100', '22', 'accessories', 'https://wyposazeniesklepow.pl/userdata/public/gfx/2084/F-100x200.png');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Papier', '200', '21', 'accessories', 'https://wyposazeniesklepow.pl/userdata/public/gfx/2084/F-100x200.png');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Papier', '300', '23', 'accessories', 'https://wyposazeniesklepow.pl/userdata/public/gfx/2084/F-100x200.png');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Papier', '400', '24', 'accessories', 'https://wyposazeniesklepow.pl/userdata/public/gfx/2084/F-100x200.png');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Papier', '500', '2', 'accessories', 'https://wyposazeniesklepow.pl/userdata/public/gfx/2084/F-100x200.png');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Papier', '600', '25', 'accessories', 'https://wyposazeniesklepow.pl/userdata/public/gfx/2084/F-100x200.png');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Papier', '700', '26', 'accessories', 'https://wyposazeniesklepow.pl/userdata/public/gfx/2084/F-100x200.png');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Papier', '800', '27', 'accessories', 'https://wyposazeniesklepow.pl/userdata/public/gfx/2084/F-100x200.png');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Papier', '900', '21', 'accessories', 'https://wyposazeniesklepow.pl/userdata/public/gfx/2084/F-100x200.png');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Papier', '000', '22', 'accessories', 'https://wyposazeniesklepow.pl/userdata/public/gfx/2084/F-100x200.png');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Papier', '100', '22', 'accessories', 'https://wyposazeniesklepow.pl/userdata/public/gfx/2084/F-100x200.png');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Papier', '200', '21', 'accessories', 'https://wyposazeniesklepow.pl/userdata/public/gfx/2084/F-100x200.png');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Papier', '300', '23', 'accessories', 'https://wyposazeniesklepow.pl/userdata/public/gfx/2084/F-100x200.png');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Papier', '400', '24', 'accessories', 'https://wyposazeniesklepow.pl/userdata/public/gfx/2084/F-100x200.png');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Papier', '500', '2', 'accessories', 'https://wyposazeniesklepow.pl/userdata/public/gfx/2084/F-100x200.png');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Papier', '600', '25', 'accessories', 'https://wyposazeniesklepow.pl/userdata/public/gfx/2084/F-100x200.png');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Papier', '700', '26', 'accessories', 'https://wyposazeniesklepow.pl/userdata/public/gfx/2084/F-100x200.png');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Papier', '800', '27', 'accessories', 'https://wyposazeniesklepow.pl/userdata/public/gfx/2084/F-100x200.png');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Papier', '900', '21', 'accessories', 'https://wyposazeniesklepow.pl/userdata/public/gfx/2084/F-100x200.png');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Papier', '000', '22', 'accessories', 'https://wyposazeniesklepow.pl/userdata/public/gfx/2084/F-100x200.png');

INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Kabel RJ45 10m', '50', '10', 'special', 'https://image.shutterstock.com/image-illustration/lan-network-connection-ethernet-cable-260nw-772490347.jpg');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Kabel RJ45 10m', '50', '10', 'special', 'https://image.shutterstock.com/image-illustration/lan-network-connection-ethernet-cable-260nw-772490347.jpg');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Kabel RJ45 20m', '90', '15', 'special', 'https://image.shutterstock.com/image-illustration/lan-network-connection-ethernet-cable-260nw-772490347.jpg');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Kabel RJ45 10m', '50', '10', 'special', 'https://image.shutterstock.com/image-illustration/lan-network-connection-ethernet-cable-260nw-772490347.jpg');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Kabel RJ45 10m', '50', '10', 'special', 'https://image.shutterstock.com/image-illustration/lan-network-connection-ethernet-cable-260nw-772490347.jpg');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Kabel RJ45 10m', '50', '10', 'special', 'https://image.shutterstock.com/image-illustration/lan-network-connection-ethernet-cable-260nw-772490347.jpg');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Kabel RJ45 10m', '50', '10', 'special', 'https://image.shutterstock.com/image-illustration/lan-network-connection-ethernet-cable-260nw-772490347.jpg');

INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `product_discount`, `image_url`) VALUES (NULL, 'Kabel RJ45 10m', '50', '10', 'special', '1', 'https://image.shutterstock.com/image-illustration/lan-network-connection-ethernet-cable-260nw-772490347.jpg');

INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Komputer i5 2500k', '1500', '5', 'computers', 'https://pngimg.com/uploads/computer_pc/computer_pc_PNG7706.png');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Komputer i7 6700k', '2500', '8', 'computers', 'https://pngimg.com/uploads/computer_pc/computer_pc_PNG7706.png');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Komputer i5 2500k', '1500', '5', 'computers', 'https://pngimg.com/uploads/computer_pc/computer_pc_PNG7706.png');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Komputer i5 2500k', '1500', '5', 'computers', 'https://pngimg.com/uploads/computer_pc/computer_pc_PNG7706.png');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Komputer i5 2500k', '1500', '5', 'computers', 'https://pngimg.com/uploads/computer_pc/computer_pc_PNG7706.png');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Komputer i5 2500k', '1500', '5', 'computers', 'https://pngimg.com/uploads/computer_pc/computer_pc_PNG7706.png');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Komputer i5 2500k', '1500', '5', 'computers', 'https://pngimg.com/uploads/computer_pc/computer_pc_PNG7706.png');



INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Laptop 1', '1500', '3', 'laptops', 'https://pngimg.com/uploads/laptop/laptop_PNG101811.png');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Laptop 2', '1800', '6', 'laptops', 'https://pngimg.com/uploads/laptop/laptop_PNG101811.png');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Laptop 1', '1500', '3', 'laptops', 'https://pngimg.com/uploads/laptop/laptop_PNG101811.png');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Laptop 1', '1500', '3', 'laptops', 'https://pngimg.com/uploads/laptop/laptop_PNG101811.png');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Laptop 1', '1500', '3', 'laptops', 'https://pngimg.com/uploads/laptop/laptop_PNG101811.png');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Laptop 1', '1500', '3', 'laptops', 'https://pngimg.com/uploads/laptop/laptop_PNG101811.png');
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_quantity`, `product_category`, `image_url`) VALUES (NULL, 'Laptop 1', '1500', '3', 'laptops', 'https://pngimg.com/uploads/laptop/laptop_PNG101811.png');

